---
env:
  TERM: xterm-256color

scrolling:
  history: 10000

window:
  decorations: buttonless
  dimensions:
    columns: 133
    lines: 40

font:
  size: 16
  normal:
    family: SauceCodePro Nerd Font
    style: Regular

  bold:
    family: SauceCodePro Nerd Font
    style: Bold

  italic:
    family: SauceCodePro Nerd Font
    style: Italic

  bold_italic:
    family: SauceCodePro Nerd Font
    style: Bold Italic

colors:
  primary:
    background: '#101421'
    foreground: '#fffbf6'

  normal:
    black: '#2e2e2e'
    red: '#eb4129'
    green: '#abe047'
    yellow: '#f6c744'
    blue: '#47a0f3'
    magenta: '#7b5cb0'
    cyan: '#64dbed'
    white: '#e5e9f0'

  bright:
    black: '#565656'
    red: '#ec5357'
    green: '#c0e17d'
    yellow: '#f9da6a'
    blue: '#49a4f8'
    magenta: '#a47de9'
    cyan: '#99faf2'
    white: '#ffffff'
