# https://www.hamvocke.com/blog/a-guide-to-customizing-your-tmux-conf/
# https://gist.github.com/ryerh/14b7c24dfd623ef8edc7
# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# switch panes using hjkl
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# resize window
bind H resize-pane -L 5
bind J resize-pane -D 5
bind K resize-pane -U 5
bind L resize-pane -R 5

set -g base-index         1
set -g display-panes-time 10000
set -g pane-base-index    1
set -g renumber-windows   on

setw -g allow-rename      off
setw -g automatic-rename  off
setw -g mode-keys         vi

# TPM
# https://github.com/tmux-plugins/tpm
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Terminal True color support
# https://github.com/tmux/tmux/issues/1246
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*256col*:Tc"

# tmux theme
# https://github.com/jimeh/tmux-themepack
set -g @plugin 'jimeh/tmux-themepack'
set -g @themepack 'powerline/double/cyan'

# useful plugin
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-open'

# history limit
set -g history-limit 100000

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'git@github.com/user/plugin'
# set -g @plugin 'git@bitbucket.com/user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
